server:
  port: 8888

spring:
  application:
    name: proxy

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    userApi:
      path: /user/*
      serviceId: user
      stringPrefix: false # false 表示不去掉user

